// GENERADO por scripts/importar-flota-melipal.py a partir del fleet.cfg
// del Melipal. No editar a mano: volver a correr el script.

import type { BuqueFlota } from './types.js';

export const FLOTA_MELIPAL: BuqueFlota[] = [
  {
    "sigla": "BALI",
    "nombre": "Balizador",
    "motores": 2,
    "desplazamientoT": 300,
    "esloraM": 53.1,
    "mangaM": 9.3,
    "caladoM": 3,
    "velMaxKn": 11.9,
    "velMinKn": -6,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 300,
      "MAN": 252,
      "HAH": 201,
      "SAH": 150,
      "DSAH": 99,
      "STOP": 0,
      "DSAS": -81,
      "SAS": -100,
      "HAS": -201,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "REMO",
    "nombre": "Remolcador",
    "motores": 2,
    "desplazamientoT": 400,
    "esloraM": 21.4,
    "mangaM": 6.28,
    "caladoM": 1.82,
    "velMaxKn": 13.98,
    "velMinKn": -7,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 320,
      "MAN": 270,
      "HAH": 200,
      "SAH": 150,
      "DSAH": 100,
      "STOP": 0,
      "DSAS": -80,
      "SAS": -100,
      "HAS": -200,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "GANG",
    "nombre": "Ganguil",
    "motores": 2,
    "desplazamientoT": 584,
    "esloraM": 65.15,
    "mangaM": 12.5,
    "caladoM": 2,
    "velMaxKn": 6.9,
    "velMinKn": -6.9,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 250,
      "MAN": 200,
      "HAH": 152,
      "SAH": 85,
      "DSAH": 45,
      "STOP": 0,
      "DSAS": -40,
      "SAS": -85,
      "HAS": -170,
      "FAS": -250
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "TAN1",
    "nombre": "Halcon del Sur",
    "motores": 2,
    "desplazamientoT": 4271,
    "esloraM": 105,
    "mangaM": 19.59,
    "caladoM": 5,
    "velMaxKn": 11.42,
    "velMinKn": -4.4,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 200,
      "MAN": 170,
      "HAH": 110,
      "SAH": 90,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -90,
      "HAS": -110,
      "FAS": -200
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "TAN2",
    "nombre": "Antares",
    "motores": 1,
    "desplazamientoT": 2500,
    "esloraM": 114.5,
    "mangaM": 20,
    "caladoM": 6.5,
    "velMaxKn": 9.49,
    "velMinKn": -7.2,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 200,
      "MAN": 170,
      "HAH": 140,
      "SAH": 90,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -90,
      "HAS": -110,
      "FAS": -200
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "CAU",
    "nombre": "Cau Cau",
    "motores": 1,
    "desplazamientoT": 303,
    "esloraM": 28.08,
    "mangaM": 9.5,
    "caladoM": 1.55,
    "velMaxKn": 16,
    "velMinKn": -4.1,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 3,
    "rpm": {
      "FAH": 300,
      "MAN": 252,
      "HAH": 180,
      "SAH": 96,
      "DSAH": 75,
      "STOP": 0,
      "DSAS": -69,
      "SAS": -138,
      "HAS": -225,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": false
  }
];
