// GENERADO por scripts/importar-flota-melipal.py a partir del fleet.cfg
// del Melipal. No editar a mano: volver a correr el script.

import type { BuqueFlota } from './types.js';

export const FLOTA_MELIPAL: BuqueFlota[] = [
  {
    "sigla": "M140",
    "nombre": "Meko 140",
    "motores": 2,
    "desplazamientoT": 1700,
    "esloraM": 92,
    "mangaM": 12,
    "caladoM": 4.5,
    "velMaxKn": 27.5,
    "velMinKn": -4.4,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 4.9,
    "rpm": {
      "FAH": 400,
      "MAN": 320,
      "HAH": 250,
      "SAH": 150,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -150,
      "HAS": -250,
      "FAS": -400
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "M360",
    "nombre": "Meko 360",
    "motores": 2,
    "desplazamientoT": 3600,
    "esloraM": 127,
    "mangaM": 19.59,
    "caladoM": 6.5,
    "velMaxKn": 31.5,
    "velMinKn": -4.4,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 4.9,
    "rpm": {
      "FAH": 400,
      "MAN": 320,
      "HAH": 250,
      "SAH": 150,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -150,
      "HAS": -250,
      "FAS": -400
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "LGPA",
    "nombre": "A.R.A PATAGONIA",
    "motores": 2,
    "desplazamientoT": 7600,
    "esloraM": 157,
    "mangaM": 20,
    "caladoM": 8.6,
    "velMaxKn": 20,
    "velMinKn": -4.4,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 4.9,
    "rpm": {
      "FAH": 400,
      "MAN": 320,
      "HAH": 250,
      "SAH": 150,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -150,
      "HAS": -250,
      "FAS": -400
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "REMO",
    "nombre": "Remolcador",
    "motores": 2,
    "desplazamientoT": 400,
    "esloraM": 21.4,
    "mangaM": 6.28,
    "caladoM": 1.82,
    "velMaxKn": 13.98,
    "velMinKn": -7,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 320,
      "MAN": 270,
      "HAH": 200,
      "SAH": 150,
      "DSAH": 100,
      "STOP": 0,
      "DSAS": -80,
      "SAS": -100,
      "HAS": -200,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "PASS",
    "nombre": "Passenger Ship",
    "motores": 1,
    "desplazamientoT": 42490,
    "esloraM": 281,
    "mangaM": 32.22,
    "caladoM": 7,
    "velMaxKn": 26.95,
    "velMinKn": -6.79,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 3,
    "rpm": {
      "FAH": 105,
      "MAN": 61,
      "HAH": 48,
      "SAH": 35,
      "DSAH": 26,
      "STOP": 0,
      "DSAS": -26,
      "SAS": -35,
      "HAS": -48,
      "FAS": -69
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "HHSS",
    "nombre": "High Speed Ship",
    "motores": 1,
    "desplazamientoT": 5,
    "esloraM": 10,
    "mangaM": 2,
    "caladoM": 0.5,
    "velMaxKn": 55.41,
    "velMinKn": -14,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 1,
    "rpm": {
      "FAH": 2000,
      "MAN": 1560,
      "HAH": 1120,
      "SAH": 720,
      "DSAH": 520,
      "STOP": 0,
      "DSAS": -380,
      "SAS": -560,
      "HAS": -720,
      "FAS": -980
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "SFID",
    "nombre": "Sfida",
    "motores": 1,
    "desplazamientoT": 303,
    "esloraM": 27,
    "mangaM": 7,
    "caladoM": 3.2,
    "velMaxKn": 10.4,
    "velMinKn": -4.1,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 3,
    "rpm": {
      "FAH": 300,
      "MAN": 252,
      "HAH": 180,
      "SAH": 96,
      "DSAH": 75,
      "STOP": 0,
      "DSAS": -69,
      "SAS": -138,
      "HAS": -225,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": true
  },
  {
    "sigla": "ARGE",
    "nombre": "Argentino",
    "motores": 1,
    "desplazamientoT": 615,
    "esloraM": 34,
    "mangaM": 8,
    "caladoM": 4,
    "velMaxKn": 11,
    "velMinKn": -4,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 377,
      "MAN": 309,
      "HAH": 286,
      "SAH": 177,
      "DSAH": 113,
      "STOP": 0,
      "DSAS": -98,
      "SAS": -135,
      "HAS": -237,
      "FAS": -377
    },
    "bowThruster": false,
    "pesquero": true
  },
  {
    "sigla": "CENT",
    "nombre": "Centauro",
    "motores": 1,
    "desplazamientoT": 772,
    "esloraM": 36,
    "mangaM": 9.3,
    "caladoM": 4.1,
    "velMaxKn": 12,
    "velMinKn": -5,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 377,
      "MAN": 309,
      "HAH": 286,
      "SAH": 180,
      "DSAH": 109,
      "STOP": 0,
      "DSAS": -79,
      "SAS": -131,
      "HAS": -271,
      "FAS": -377
    },
    "bowThruster": false,
    "pesquero": true
  },
  {
    "sigla": "40ES",
    "nombre": "Don Luis",
    "motores": 1,
    "desplazamientoT": 500,
    "esloraM": 40,
    "mangaM": 10,
    "caladoM": 2,
    "velMaxKn": 17.85,
    "velMinKn": -8.9,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 300,
      "MAN": 270,
      "HAH": 201,
      "SAH": 150,
      "DSAH": 78,
      "STOP": 0,
      "DSAS": -78,
      "SAS": -102,
      "HAS": -150,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": true
  },
  {
    "sigla": "BALI",
    "nombre": "Balizador",
    "motores": 2,
    "desplazamientoT": 300,
    "esloraM": 53.1,
    "mangaM": 9.3,
    "caladoM": 3,
    "velMaxKn": 11.9,
    "velMinKn": -6,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 300,
      "MAN": 252,
      "HAH": 201,
      "SAH": 150,
      "DSAH": 99,
      "STOP": 0,
      "DSAS": -81,
      "SAS": -100,
      "HAS": -201,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "GANG",
    "nombre": "Ganguil",
    "motores": 2,
    "desplazamientoT": 584,
    "esloraM": 65.15,
    "mangaM": 12.5,
    "caladoM": 2,
    "velMaxKn": 6.9,
    "velMinKn": -6.9,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 250,
      "MAN": 200,
      "HAH": 152,
      "SAH": 85,
      "DSAH": 45,
      "STOP": 0,
      "DSAS": -40,
      "SAS": -85,
      "HAS": -170,
      "FAS": -250
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "70ES",
    "nombre": "Argos",
    "motores": 2,
    "desplazamientoT": 1000,
    "esloraM": 70,
    "mangaM": 20,
    "caladoM": 3,
    "velMaxKn": 14.9,
    "velMinKn": -5.45,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 200,
      "MAN": 170,
      "HAH": 140,
      "SAH": 90,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -90,
      "HAS": -150,
      "FAS": -200
    },
    "bowThruster": false,
    "pesquero": true
  },
  {
    "sigla": "100M",
    "nombre": "Siempre San Salvador",
    "motores": 2,
    "desplazamientoT": 2000,
    "esloraM": 100,
    "mangaM": 20,
    "caladoM": 4,
    "velMaxKn": 11.82,
    "velMinKn": -7.15,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 400,
      "MAN": 320,
      "HAH": 252,
      "SAH": 172,
      "DSAH": 88,
      "STOP": 0,
      "DSAS": -76,
      "SAS": -168,
      "HAS": -272,
      "FAS": -400
    },
    "bowThruster": false,
    "pesquero": true
  },
  {
    "sigla": "TAN1",
    "nombre": "Halcon del Sur",
    "motores": 2,
    "desplazamientoT": 4271,
    "esloraM": 105,
    "mangaM": 19.59,
    "caladoM": 5,
    "velMaxKn": 11.42,
    "velMinKn": -4.4,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 200,
      "MAN": 170,
      "HAH": 110,
      "SAH": 90,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -90,
      "HAS": -110,
      "FAS": -200
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "TAN2",
    "nombre": "Antares",
    "motores": 1,
    "desplazamientoT": 2500,
    "esloraM": 114.5,
    "mangaM": 20,
    "caladoM": 6.5,
    "velMaxKn": 9.49,
    "velMinKn": -7.2,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 5,
    "rpm": {
      "FAH": 200,
      "MAN": 170,
      "HAH": 140,
      "SAH": 90,
      "DSAH": 60,
      "STOP": 0,
      "DSAS": -60,
      "SAS": -90,
      "HAS": -110,
      "FAS": -200
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "CONT",
    "nombre": "Container Ship",
    "motores": 1,
    "desplazamientoT": 22530,
    "esloraM": 150,
    "mangaM": 27.1,
    "caladoM": 8.5,
    "velMaxKn": 19.6,
    "velMinKn": -8.53,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 1,
    "rpm": {
      "FAH": 135,
      "MAN": 90,
      "HAH": 75,
      "SAH": 60,
      "DSAH": 38,
      "STOP": 0,
      "DSAS": -38,
      "SAS": -60,
      "HAS": -75,
      "FAS": -98
    },
    "bowThruster": true,
    "pesquero": false
  },
  {
    "sigla": "BULK",
    "nombre": "Bulk Carrier",
    "motores": 1,
    "desplazamientoT": 40000,
    "esloraM": 206,
    "mangaM": 31.8,
    "caladoM": 8.5,
    "velMaxKn": 17.49,
    "velMinKn": -6.25,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 4.5,
    "rpm": {
      "FAH": 120,
      "MAN": 108,
      "HAH": 96,
      "SAH": 76,
      "DSAH": 45,
      "STOP": 0,
      "DSAS": -45,
      "SAS": -70,
      "HAS": -87,
      "FAS": -96
    },
    "bowThruster": true,
    "pesquero": false
  },
  {
    "sigla": "VLCC",
    "nombre": "Very Large Crude Carrier",
    "motores": 1,
    "desplazamientoT": 92960,
    "esloraM": 305,
    "mangaM": 47.2,
    "caladoM": 9.5,
    "velMaxKn": 17.15,
    "velMinKn": -6.03,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 3.5,
    "rpm": {
      "FAH": 80,
      "MAN": 72,
      "HAH": 54,
      "SAH": 39,
      "DSAH": 19,
      "STOP": 0,
      "DSAS": -14,
      "SAS": -28,
      "HAS": -37,
      "FAS": -65
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "ALUC",
    "nombre": "AluCat",
    "motores": 1,
    "desplazamientoT": 10,
    "esloraM": 11.45,
    "mangaM": 3.76,
    "caladoM": 0.6,
    "velMaxKn": 28,
    "velMinKn": -9,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 1,
    "rpm": {
      "FAH": 2800,
      "MAN": 156,
      "HAH": 112,
      "SAH": 72,
      "DSAH": 52,
      "STOP": 0,
      "DSAS": -380,
      "SAS": -560,
      "HAS": -720,
      "FAS": -980
    },
    "bowThruster": false,
    "pesquero": false
  },
  {
    "sigla": "CAU",
    "nombre": "Cau Cau",
    "motores": 1,
    "desplazamientoT": 303,
    "esloraM": 28.08,
    "mangaM": 9.5,
    "caladoM": 1.55,
    "velMaxKn": 16,
    "velMinKn": -4.1,
    "anguloTimonMaxDeg": 35,
    "velTimonDegPorSeg": 3,
    "rpm": {
      "FAH": 300,
      "MAN": 252,
      "HAH": 180,
      "SAH": 96,
      "DSAH": 75,
      "STOP": 0,
      "DSAS": -69,
      "SAS": -138,
      "HAS": -225,
      "FAS": -300
    },
    "bowThruster": false,
    "pesquero": false
  }
];
